name: super_editor
description: Configurable, composable, extensible text editor and document renderer for Flutter.
version: 0.2.2
homepage: https://github.com/superlistapp/super_editor
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  characters: ^1.2.0
  collection: ^1.15.0
  http: ^0.13.1
  linkify: ^4.0.0
  logging: ^1.0.1
  uuid: ^3.0.3

  super_text_layout:
    git:
      url: https://github.com/hieupham-anfin/super_text_layout.git
      path: super_text_layout

  # Dependencies for testing tools that we ship with super_editor
  flutter_test:
    sdk: flutter

flutter:
  # no Flutter configuration
